// VoiceService
// Orchestrates: record audio (native Android cacheDir) → transcribe via OpenAI Whisper.
// No path_provider needed — path generated on Kotlin side.
// No language field → Whisper auto-detects Hindi / Marathi / English / any language.

import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;
import 'package:http_parser/http_parser.dart';
import 'audio_recorder_service.dart';
import '../config/app_config.dart';

class VoiceService {
  static const _whisperUrl =
      'https://api.openai.com/v1/audio/transcriptions';

  final _recorder = AudioRecorderService();
  String? _recordingPath;

  /// Start recording. Returns the file path (generated by Android).
  Future<void> startRecording() async {
    _recordingPath = await _recorder.startRecording();
  }

  /// Stop recording. Returns the path of the saved audio file.
  Future<String?> stopRecording() async {
    return _recorder.stopRecording();
  }

  /// Transcribe audio file at [filePath] using OpenAI Whisper-1.
  Future<String> transcribe(String filePath) async {
    final file = File(filePath);
    if (!file.existsSync()) {
      throw Exception('Audio file not found: $filePath');
    }

    final request = http.MultipartRequest('POST', Uri.parse(_whisperUrl))
      ..headers['Authorization'] = 'Bearer ${AppConfig.openAiApiKey}'
      ..fields['model'] = 'whisper-1'
      // No 'language' = auto-detect Hindi, Marathi, English, etc.
      ..files.add(await http.MultipartFile.fromPath(
        'file',
        filePath,
        contentType: MediaType('audio', 'm4a'),
      ));

    final streamed = await request.send();
    final response = await http.Response.fromStream(streamed);

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body) as Map<String, dynamic>;
      final text = (data['text'] as String?)?.trim() ?? '';
      if (text.isEmpty) throw Exception('No speech detected. Please try again.');
      return text;
    } else {
      final err = jsonDecode(response.body);
      throw Exception(
        'Whisper ${response.statusCode}: ${err['error']?['message'] ?? 'Unknown error'}',
      );
    }
  }
}
